### ISSUE TITLE
Vagrant up starts qemu VM as read-only

### ISSUE THREAD

**Issue by Jokeswar** [vmck/image-builder#4]
Here is the [dmesg log](https://gist.github.com/Jokeswar/da66b0f1842673a74d27162f1329cc9f) of a job started through vagrant-vmck. It seems that the system fails and boots in read-only mode. From line [469](https://gist.github.com/Jokeswar/da66b0f1842673a74d27162f1329cc9f#file-dmesg-log-L468) downwards the error `EXT4-fs error` appears. [Here](https://jenkins.liquiddemo.org/vmck/image-builder/161/1/2) is the build which created the image that was used in this job. During testing, when the image was started with qemu, it was able to create a file and the system wasn't read-only. What I believe is that either Nomad does something fishy or vmck's job specification has some conflicting arguments. Previous images that weren't built using packer work just fine. It's fishy! @mgax @gabriel-v

**Comment by mgax** [comment]
> either Nomad does something fishy or vmck's job specification has some conflicting arguments

It's highly unlikely that there's a bug in nomad. Same for vmck jobs, they work flawlessly for the current CI runs.

> Previous images that weren't built using packer work just fine.

So maybe we're using packer wrong. [line 471](https://gist.github.com/Jokeswar/da66b0f1842673a74d27162f1329cc9f#file-dmesg-log-L471) (`Journal file corrupted, rotating.`) suggests the disk image is corrupted. Maybe we're not stopping the build vm cleanly. In the build logs you [linked](https://jenkins.liquiddemo.org/vmck/image-builder/161/1/2) above, between line 3534 (`Gracefully halting virtual machine`) and 3538 (`VM shut down`) no time seems to pass, and line 3536 actually says `[ERROR] Remote command exited without exit status or exit signal.` - something is wrong there. Try running the packer build steps locally to get a better feel for how long they take and what the VM does at each step. See if you can enable more verbose logging. Or start from a minimal example from the packer docs and slowly add back our stuff and see when the error shows up.

**Comment by Jokeswar** [comment]
Solved in #3. I was archiving the `qcow2` image while the vm was running and writing to that image.
